# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e822de6b7f61eadc312ffc50b8db44f622a2715cc58744f4cbed825a75fc1631d1ba06c970857efdafb944f33452110eeb9c3d4154ca68852b5def3d53a2751a
  flickr_api_key: 4665ef6fd72427931c8c09129cd44b5d
  flickr_shared_secret: 4dfa5ab177cb4971

test:
  secret_key_base: 701de0ea6623520f011fee57c5e0ed99f2271cb6b8a546afaf87f5a54ca35b8296b771b34d5ad6db157a0ddf51093c88e50c6435adda94bc401c105f203a4c31
  flickr_api_key: 4665ef6fd72427931c8c09129cd44b5d
  flickr_shared_secret: 4dfa5ab177cb4971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: notusingcookiesrightnowsodontcareaboutsecretbasekey
  flickr_api_key: 4665ef6fd72427931c8c09129cd44b5d
  flickr_shared_secret: 4dfa5ab177cb4971